### ISSUE TITLE
Dicekeys.app unable to scan dice.

### ISSUE THREAD

**Issue by simonssay** [dicekeys/beta-program#10]
I have a Google Pixel 3a  with the latest system updates installed and when I tell dicekeys.app to scan the tray, it detects my cameras and then selects the rear camera but then all I get is a frozen image. 

I have managed to get the dice in the frame but it looks like it is just a frozen pic and never proceeds to scan anything. At that point, I can select one of the two cameras from list below the image but the image never refreshes or makes any attempt to try again. I can only get it to try again by refreshing the page and starting over. I even tried running the site in Desktop mode with the same results.

After closing every other open site in Chrome and then closing the Chrome app and then tapping my saved shortcut for dicekeys.app, I was able to successfully scan in the dice after a few tries. It is almost as if the site took a while to load the program.

But that success was short lived. I tried it again and we are back to the same issue of a frozen image and no progress and completely closing the browser and opening up again had no effect this time.

Let me know what I can do to help as I would really like a consistent android phone experience.

Thanks you for your time.

-Simon

**Comment by UppaJung** [comment]
Thanks.  I'm working to get some scanning stability improvements in over the next few days.

**Comment by UppaJung** [comment]
Please let me know if the version at https://staging.dicekeys.app/ resolves this issue.

**Comment by simonssay** [comment]
The version at https://staging.dicekeys.app/ resolved the issue and worked perfectly. Now the main dicekeys.app version is working great as well! No need for the desktop version setting and it continues to work with other browser tabs open.
I am sorry my response took so long. Have not had the time to look at this again after I had issues with the app initially.
Now to see how to get password set up in my apps.

Thank you for being so responsive.

**Comment by UppaJung** [comment]
Great to hear.  Thanks!
