### ISSUE TITLE
test photos for app/algorithm with different backgrounds / angles / lighting / etc

### ISSUE THREAD

**Issue by p0lt** [dicekeys/beta-program#11]
If you would like photos of other specific conditions please request and I will get some more to post.

![20200920_155238](https://user-images.githubusercontent.com/44121959/93964936-adc91b00-fd15-11ea-96f9-582ffd33667a.jpg)
![20200920_155258](https://user-images.githubusercontent.com/44121959/93964955-b7eb1980-fd15-11ea-9a41-3d715e08a733.jpg)
![20200920_155315](https://user-images.githubusercontent.com/44121959/93964960-bae60a00-fd15-11ea-9d0e-a60a4c506dad.jpg)
![20200920_155355](https://user-images.githubusercontent.com/44121959/93964968-be799100-fd15-11ea-8590-3b5009722fed.jpg)
![IMG_20200920_154538](https://user-images.githubusercontent.com/44121959/93964982-c76a6280-fd15-11ea-82de-e2d9ad586a38.jpg)
![IMG_20200920_154601](https://user-images.githubusercontent.com/44121959/93964989-cafde980-fd15-11ea-8b28-9cb6392f1313.jpg)
![IMG_20200920_154634](https://user-images.githubusercontent.com/44121959/93964997-cfc29d80-fd15-11ea-977e-43ef433922a0.jpg)
![IMG_20200920_162543](https://user-images.githubusercontent.com/44121959/93965017-dea95000-fd15-11ea-8c90-15f14d51ede8.jpg)
![IMG_20200920_162614](https://user-images.githubusercontent.com/44121959/93965020-e2d56d80-fd15-11ea-921b-9070c1edbcc6.jpg)
![IMG_20200920_170128](https://user-images.githubusercontent.com/44121959/93965032-e79a2180-fd15-11ea-991d-8e8e668b2b7d.jpg)

**Comment by UppaJung** [comment]
Thanks.  I've moved these to the test-image repository
