### ISSUE TITLE
scan dicekeys with top in place hard to recognize

### ISSUE THREAD

**Issue by p0lt** [dicekeys/beta-program#14]
do not worry about the pictures posted on this issue. they are not my final secret dice configuration. i removed the tabs that lock the top of the box in place so i can test the dicekeys system more thouroughly. if more photos of top on configuration are needed please request more and i will post.

while trying to scan the dice with the box top in place - the thickness of the dice dividers cause directional drop shadows which seems to confuse the dice recognition. you have to try longer to get the dice to correctly recognize - tilting box and camera to get the shadows lessened or removed to get it to recognize easier.

![IMG_20200921_143249](https://user-images.githubusercontent.com/44121959/93967164-70678c00-fd1b-11ea-979f-2771f02fd306.jpg)
![IMG_20200921_143339](https://user-images.githubusercontent.com/44121959/93967172-73627c80-fd1b-11ea-91b9-58e8fe8f2043.jpg)
![IMG_20200921_143421](https://user-images.githubusercontent.com/44121959/93967175-752c4000-fd1b-11ea-8218-f136a6233189.jpg)
![IMG_20200921_143500](https://user-images.githubusercontent.com/44121959/93967177-76f60380-fd1b-11ea-8593-f572e25d3128.jpg)

**Comment by yeliaBdE** [comment]
I've had the same experience as well.

**Comment by UppaJung** [comment]
Two of these actually scan perfectly (see images below), including one where the lighting might have been challenging.  The other two images are ones where I would hope our algorithm can be improved to do better.  They are now issues #37 and #38.  All images are integrated into the testbed.

![image](https://user-images.githubusercontent.com/8259431/94353493-af476a00-00ac-11eb-92d0-649382c8052a.png)

![image](https://user-images.githubusercontent.com/8259431/94353502-bec6b300-00ac-11eb-8c47-fda3f0bb9add.png)
