### ISSUE TITLE
DICEKEY.app

### ISSUE THREAD

**Issue by pfmoose** [dicekeys/beta-program#2]
I'm waiting for my beta hardware.

In the meantime I'm have a problem scanning a generated dicekey on my android or ipad.  I used to be able to but now the picture just freezes.

For example I create a random DiceKey for testing on my laptop and then scan the DiceKey from my android or ipad.  It was working but not anymore.  Note I'm using chrome, ducktogo, and samsung browser on my android.  I'm using safari and chrome on my ipad pro.

**Comment by UppaJung** [comment]
Hi @pfmoose,

   I was able to reproduce a freeze in issue #3, which I fixed.

   If you see a freeze again, please go into debug mode into your browser and see if there are any exceptions.  If so, please copy them like in #3.  I can provide more detailed instructions if you need.

   If the problem is now gone, please let me know as well!

   Thanks for the bug report!

**Comment by pfmoose** [comment]
This is on my Samsung Note 10+ android and Chrome.  I'm NOT sure how to get to debug mode in the browser on the android.  

It is working intermittently on same device using the samsung browser.  I keep refreshing the page till it unfreezes.  That isn't working in Chrome however.

**Comment by pfmoose** [comment]
After further investigation it seems like the app doesn't go into the video mode on the android. I noticed it's working outstandingly in iOS and Safari.

**Comment by UppaJung** [comment]
Thanks.  I'm planning to put in more diagnostics and error reporting in the
next 24-48 hours.

**Comment by pfmoose** [comment]
I got my beta test hardware on Friday. I should have photos soon as part of the beta testing. NOTE: I did file the 4 side tabs so the top does NOT lock in place but allow the box to be reused with new dicekeys.

The dicekeys app works great with a Windows 10 surface pro and iPad Pro (Safari). Samsung Note 10 + effectively does not work because it does not go into video mode. If it does goto video it eventually works. I did get your error notification ie is this an E5 yes no. Definitely more fiddly getting the image to register when it goes to video mode.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by UppaJung** [comment]
The new diagnostics should be in there.  Hopefully it provides more
information instead of freezing.  Let me know!  Thanks!

**Comment by pfmoose** [comment]
On the android I can't access the diagnostics. It's still hit and miss going to video mode.  When it does go to video, it's working.  

Also if I close Chrome and restart Chrome, it the same process trying to go into video.

NOTE: to more successful register the dicekeys I have start from afar and slowly move in.

**Comment by pfmoose** [comment]
I'm having more success today on my android and Chrome. If the video mode doesn't come up, I swipe up from the bottom of the screen. So a combination of refresh and swiping seems to work. 

Again as soon the video becomes active i not having problems. I position the camera at a distance i slowly move it closer. As I see the green images I have the sweet spot and just readjust the camera by tilting and rotating.

I have zero problem with my iPad version 14 and safari.

**Comment by pfmoose** [comment]
I've been able to get video mode to come up consistently.

I select the camera label rear/front at the bottom of the image. I moved up or down and release. i can advise that within less than 5 secs the video mode appears then i can register the image.

**Comment by UppaJung** [comment]
Let me know if the version at https://staging.dicekeys.app resolves this.

**Comment by pfmoose** [comment]
staging.dicekeys.app has resolved it.  I had to select the second rear camera on the Samsung Note + for it to successfully registered the dicekey. Thanks for the improvement.

**Comment by UppaJung** [comment]
Can you send a screenshot? If I know the OS code I may be able to make it
select camera 2 automatically

**Comment by pfmoose** [comment]
I am mistaken, it is working fine for either camera.  I still have to go farther out with the whole box in the frame.  I then move the camera slowly forward for the dicekeys to register.  

I would say I have a 99% success rate on both my android and iOS devices.

**Comment by UppaJung** [comment]
Great
