### ISSUE TITLE
Web app eats phone battery

### ISSUE THREAD

**Issue by fruiz500** [dicekeys/beta-program#22]
iPhone SE battery level went from nearly 100% to around 60% after barely 5 minutes of (unsuccessful) use from Safari, plus half-hour of non-use. It seems the app kept either the camera or the processing going after it was closed.

The app took shots at irregular intervals of around 10 seconds. The closest the app got to recognizing the code is the picture below.
![IMG_4212](https://user-images.githubusercontent.com/2514292/94167319-fdacfc80-fe51-11ea-81a3-314ccda31671.jpg)

**Comment by UppaJung** [comment]
Please let me know if the version at https://staging.dicekeys.app/ resolves this issue with the camera not being freed and processing not turning off.  During the scanning process (which should hopefully take 5 seconds, not 5 minutes) there's not much to be done to reduce power usage other than to get a native app out.

**Comment by fruiz500** [comment]
I can confirm that the version of Sept. 25 morning does not eat battery like yesterday's version did. Unfortunately, there is no image in an iPhone SE under Safari and iOS 14.0.1. Chrome never gets to select the camera successfully, in the same device.

![IMG_4215](https://user-images.githubusercontent.com/2514292/94290245-8c3b7f80-ff1f-11ea-87af-1cee80e836b9.jpg)
