### ISSUE TITLE
Request: add option to output raw code instead of words

### ISSUE THREAD

**Issue by fruiz500** [dicekeys/beta-program#23]
I'm envisioning the use of a DiceKeys set as a quick way to generate high-quality entropy for games and applications (not necessarily cryptographic). This requires a way to output the unique code (decimal, hex, or other standard format) corresponding to the dice position. Even better if reduction to canonical orientation is not done, or at least can be turned off. Even better if the user can choose the output base.

Plus, reduction to 15 words out of a 1024 dictionary wastes a lot of entropy. It should be possible to do better.

**Comment by yeliaBdE** [comment]
Agreed with wanting to make use of DiceKey in the way mentioned above; being able to expose the numerical output of the generated bits has value, I think.

I cannot comment on the "15 words" part of the issue, though...

**Comment by p0lt** [comment]
i also agree raw output of the dice would be good to have available

**Comment by ukscone** [comment]
+1 on raw output

**Comment by UppaJung** [comment]
Moving this to #29 which is more specific for format.  See also #27.
