### ISSUE TITLE
Would there be value in a larger base?

### ISSUE THREAD

**Issue by yeliaBdE** [dicekeys/beta-program#24]
I'll be the first to admit that I am but a babe in the woods when it comes to many things cryptographic, but I found myself wondering if there would be goodness to having a base that is, say, 10X10 into which the 25 DiceKey dice are cast. It seems to this neophyte that this would add another level of "randomness" in the form of which of the 100 base spaces has a dice and which don't.

Anyway, just a random thought...

**Comment by UppaJung** [comment]
The cryptographers on our advisory board feel 196 bits is plenty, but if we wanted more a 6x6 grid with 36 dice would be a smaller form factor and take the bit strength into the beyond-ridiculous levels.

**Comment by yeliaBdE** [comment]
Fair enough; like I said, "neophyte" :-)
