### ISSUE TITLE
Removing dice from plastic bag

### ISSUE THREAD

**Issue by djlambert** [dicekeys/beta-program#32]
If the corner(s) of the plastic bag were perforated so they could easily be torn off it would help transferring the dice from the to the base. The dice could be "poured" through the corner - similar to a pastry bag.

Alternatively you could print a dashed line with a scissor icon on the bag, or even more simply recommend this in the instructions.

I found it much easier to get all the dice in the base, instead of some on my desk, through a cut corner.

**Comment by fruiz500** [comment]
You want to avoid guiding the "die nozzle" yourself so the dice pour into empty areas of the tray, rather than the desk. Any human intervention reduces the entropy of the result.

**Comment by UppaJung** [comment]
We encourage users to roll the dice in the felt bag and not the plastic one.  In the felt bag, you can shake them up to get randomness, and then use the draw strings to create the pastry bag effect.
