### ISSUE TITLE
Suggestion: Use QR codes

### ISSUE THREAD

**Issue by fruiz500** [dicekeys/beta-program#35]
I'm sure you must have considered this possibility already, but here it is anyway. QR codes have built-in error correction and space for a logo, which in this case would be the human-readable letter + number codes. They may work better than the bar codes currently in use. The trick is finding a library that would read a whole bunch of QR codes at once, or in a tight sequence.

**Comment by UppaJung** [comment]
We've received that suggestion a few times before.  The QR codes can contain some form of logo, but it would be much less readable and distracting to the user.  Users would have a greater feeling that there was information there that they just couldn't see and that there was more than meets the eye.

If the lighting allows us to recognize a QR code, we should be able to recognize our less-visually-obtrusive underline and overline codes.
