### ISSUE TITLE
Should we switch to dice with a matte finish?

### ISSUE THREAD

**Issue by UppaJung** [dicekeys/beta-program#41]
Under certain lighting conditions, dice can reflect back the light source (glare) can interfere with scanning.

Our dice manufacturer suggested a matte finish might reduce that problem.  We ordered some dice with a matte finish to compare. We were concerned that the glossy coating might help protect the image on the dice and that removing it might make the dice more vulnerable to the elements.  To test this hypothesis, we submerged dice to 34 hours in chlorine bleach (a base) and 34 hours in lemon juice (an acid) 

We tested a 12mm matte die (left) a 16mm sample engraved die (center), and a 12mm glossy die from the beta.

![before](https://user-images.githubusercontent.com/8259431/94506317-0df51b00-0248-11eb-8116-586dcda292fc.jpg)

None of the dice, included the die with the matte finish, showed any damage from the 68 hours of exposure (see below).

![after](https://user-images.githubusercontent.com/8259431/94506326-10f00b80-0248-11eb-85c4-a13f587df940.jpg)

Please vote with a thumbs up if you think we should move to the matte dice and a thumbs down if you think we should stick to the glossy dice used in the beta.  To vote, look for the smiley emoji icon at the top right of this text box.

Comments welcome as well!

**Comment by yeliaBdE** [comment]
I've given my thumbs-up already for the matte dice, but my feeling is that the test should've included a bit of mechanical abrasion in addition to the chemical attack. Basically, how much rubbing is required to damage the image on a matte dice--would rubbing it with a fingernail start to lift the image? How about rubbing for a few minutes against a rough cloth (say, denim)? If it were to hold up well to this kind of treatment it's probably sufficiently robust to work in this application; it's not like these are going to be carried loose in a person's pocket as part of their EDC, after all...

The engraved dice is disappointing both in terms of the quality of the engraved image, and the specular reflections within the engraved portions. I would've thought the engraving would've been the absolute best solution, both in terms of ease of scanning as well as the indelible nature of the images. But, alas, that seems not to be the case.

**Comment by fruiz500** [comment]
Anything that will help the software to recognize the dice better is a good idea. In my tests, recognition has failed often, though this may be caused more by shadows than by reflections.

**Comment by 1cyberwarrior** [comment]
I vote for using the Matte dice.

**Comment by timshadel** [comment]
My opinion is to pick the one which can most easily pass for Sharpie. If I lose a die, then I'd love to replace it by finding a die that's roughly the size and then drawing the various sides on labels to stick to the replacement. As long as the image capture can recognize pen/fine Sharpie with some ok-ish % of success then I say pick whichever optimizes the most likely scenario (I have all my dice) while not making the Sharpie impossible.

**Comment by hmmmbacon** [comment]
I don't know. When I took the photos to send to you, there was a glare that I could not get rid of. On the other hand, scanning into apps there were problems also and don't know if it was glare or just a nut behind the steering wheel. I did notice that the more I scanned, the less time it took to get it right. So probably my fault. So I'll go with the majority opinion.

**Comment by djlambert** [comment]
I agree with @fruiz500, whatever finish works better with the image recognition.

**Comment by jeff3f** [comment]
I like the beta dice (glossy?) just fine as they are. I haven't spent time trying to image them under different conditions. I'm not smart enough to figure out how to vote, and it's possibly too late anyway. 👎  (this was an accident by the way)
