### ISSUE TITLE
Perform basic mechanical abrasion test on matte dice

### ISSUE THREAD

**Issue by UppaJung** [dicekeys/beta-program#46]
I've given my thumbs-up already for the matte dice, but my feeling is that the test should've included a bit of mechanical abrasion in addition to the chemical attack. Basically, how much rubbing is required to damage the image on a matte dice--would rubbing it with a fingernail start to lift the image? How about rubbing for a few minutes against a rough cloth (say, denim)? If it were to hold up well to this kind of treatment it's probably sufficiently robust to work in this application; it's not like these are going to be carried loose in a person's pocket as part of their EDC, after all...

The engraved dice is disappointing both in terms of the quality of the engraved image, and the specular reflections within the engraved portions. I would've thought the engraving would've been the absolute best solution, both in terms of ease of scanning as well as the indelible nature of the images. But, alas, that seems not to be the case.

_Originally posted by @yeliaBdE in https://github.com/dicekeys/beta-program/issues/41#issuecomment-700694352_

**Comment by dragon788** [comment]
I was just thinking about this from a vibration/dust/debris scratching standpoint, and really the box is ingeniously designed, because the face with the only important information is visible and isn't touched by anything when covered by the lid, any contaminants or potentially damaging debris shouldn't be able to get in, and if it does while the lid is open, a quick flip and tap should get it out, and unless it has fairly significant mass and isn't removed shouldn't really be able cause any long term damage unless you leave the dice keys sitting under the seat in your car for a couple years rattling around.

**Comment by jeff3f** [comment]
The beta dice are like "normal" dice in that they are a bit shiny, and they seem decently resistant to handling (grinding a handful of them together in fist, light fingernail scraping, even a test bite). I feel like a modern cell phone camera should be able to take a good picture of glossy dice provided it's not harshly lit or in direct sunlight, but I haven't spent time playing with imaging the dice (the app currently not working on my iOS 14.0.1 iphone - that's already filed).

I think a light amount of play is normal for this product, but at some point the dice should be locked away in the box, and not used again except for imaging.

**Comment by UppaJung** [comment]
I put 6 matte dice in my hands and tried to scratch them against each other for as hard as I possibly could for a couple of minutes.  As you can see from the image, it is _possible_ to scuff them so that some tiny markings scrape off (see the B5 bottom center) and some dice get small amounts of markings from the other dice (the top center die, below the underline).  It took a great deal of intense scraping to cause these relatively-small scuffs, so I would not consider this normal wear or something one would expect to happen while creating a DiceKey by rolling the dice in a bag or shaking them in one's hands.

![20201010_090625 (2)](https://user-images.githubusercontent.com/8259431/95640581-5af2b000-0ad8-11eb-93af-0245617e3555.jpg)

People who want to generate 100s of keys instead of using the product for the primarily intended purpose may want the glossy option.
